export type MedicationFamily = {
	id: number;
	code: string;
	name: string;
	description: string;
	isActive: boolean;
};

export type Medication = {
	id: number;
	familyId: number;
	family: MedicationFamily;
	code: string;
	name: string;
	genericName: string;
	manufacturer: string;
	description: string;
	isActive: boolean;
};

export type MedicationPresentation = {
	id: number;
	medicationId: number;
	medication: Medication;
	code: string;
	dosage: string;
	form: string;
	route: string;
	unit: string;
	packaging: string;
	isActive: boolean;
	createdAt: string;
	updatedAt: string;
};

export type StockStatus = 'AVAILABLE' | 'LOW_STOCK' | 'OUT_OF_STOCK';
export type PresentationAvailability = {
	presentationId: number;
	commercialName: string;
	genericName: string;
	family: string;
	dosage: string;
	form: string;
	route: string;
	unit: string;
	packaging: string;
	availableQuantity: number;
	alertThreshold: number;
	stockStatus: StockStatus;
	isActive: boolean;
};
export type PharmacyStock = {
	id: number;
	presentationId: number;
	presentation: MedicationPresentation;
	quantityAvailable: number;
	alertThreshold: number;
	isStockManaged: boolean;
	status: string;
	createdAt: string;
	updatedAt: string;
};
export type PharmacyBatch = {
	id: number;
	presentationId: number;
	presentation: MedicationPresentation;
	batchNumber: string;
	quantityReceived: number;
	quantityRemaining: number;
	expirationDate: string | null;
	supplier: string;
	isActive: boolean;
	createdAt: string;
	updatedAt: string;
};
export type StockMovement = {
	id: number;
	presentationId: number;
	presentation: MedicationPresentation;
	batchId: number | null;
	batch?: PharmacyBatch | null;
	type: string;
	quantity: number;
	stockBefore: number;
	stockAfter: number;
	reason: string;
	referenceType: string;
	referenceId: number | null;
	performedById: number | null;
	performedByName: string;
	createdAt: string;
};
export type PrescriptionQueueItem = {
	prescriptionId: number;
	consultationId: number;
	presentationId: number;
	medicationName: string;
	genericName: string;
	family: string;
	patientId: number;
	patientName: string;
	patientCode: string;
	doctorName: string;
	service: string;
	prescribedAt: string;
	dosage: string;
	form: string;
	route: string;
	prescribedQuantity: number;
	dispensedQuantity: number;
	remainingQuantity: number;
	duration: string;
	instructions: string;
	status: 'PENDING' | 'PARTIAL' | 'COMPLETED';
	availableQuantity: number;
	stockStatus: StockStatus;
};
export type Dispensation = {
	id: number;
	presentationId: number;
	presentation: MedicationPresentation;
	quantity: number;
	status: string;
	patientId: number;
	referenceId: number | null;
	notes: string;
	dispensedById: number;
	dispensedByName: string;
	items: Array<{ id: number; batchId: number; quantity: number; batch: PharmacyBatch }>;
	createdAt: string;
};

export type PharmacyVoucherStatus = 'PENDING' | 'PARTIAL' | 'COMPLETED' | 'CANCELLED';
export type PharmacyVoucherLine = {
	id: number;
	prescriptionId: number;
	presentationId: number;
	commercialName: string;
	genericName: string;
	dosage: string;
	form: string;
	route: string;
	unit: string;
	prescribedQuantity: number;
	dispensedQuantity: number;
	remainingQuantity: number;
	availableQuantity: number;
	stockStatus: StockStatus;
	status: PharmacyVoucherStatus;
};
export type PharmacyVoucher = {
	id: number;
	number: string;
	consultationId: number;
	patientId: number;
	patientName: string;
	patientCode: string;
	service: string;
	prescriber: string;
	isInsured: boolean;
	insuranceName?: string;
	status: PharmacyVoucherStatus;
	lineCount: number;
	lines?: PharmacyVoucherLine[];
	createdAt: string;
};
export type PharmacyVoucherList = {
	items: PharmacyVoucher[];
	page: number;
	pageSize: number;
	total: number;
};
